name: bedrock
recipe: wordpress
config:
  php: 8.1 
  composer_version: 2-latest
  webroot: web
  database: mariadb
  xdebug: true

proxy:
  appserver:
    - bedrock.lndo.site

tooling:
  node:
    service: theme
  yarn:
    service: theme

excludes:
  - vendor
  - node_modules